apiVersion: run.tanzu.vmware.com/v1alpha1      #TKG API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: k8-cluster-medium                          #cluster name, user defined
spec:
  distribution:
    version: v1.17.7+vmware.1-tkg.1.154236c    #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: best-effort-xsmall                 #vmclass for control plane nodes
      storageClass: pacific-gold-storage-policy         #storageclass for control plane
    workers:
      count: 2                                 #number of worker nodes
      class: best-effort-xsmall                 #vmclass for worker nodes
      storageClass: pacific-gold-storage-policy         #storageclass for worker nodes
