apiVersion: run.tanzu.vmware.com/v1alpha1      #TKG API endpoint
kind: TanzuKubernetesCluster                   #required parameter
metadata:
  name: k8-cluster-small                          #cluster name, user defined
spec:
  distribution:
    version: v1.16.8+vmware.1-tkg.3.60d2ffd   #resolved kubernetes version
  topology:
    controlPlane:
      count: 1                                 #number of control plane nodes
      class: best-effort-small                 #vmclass for control plane nodes
      storageClass: pacific-gold-storage-policy         #storageclass for control plane
    workers:
      count: 1                                 #number of worker nodes
      class: best-effort-small                 #vmclass for worker nodes
      storageClass: pacific-gold-storage-policy         #storageclass for worker nodes
